version: '3.8'

services:
  dev_db:
    image: postgres:16.0
    container_name: dev_db
    environment:
      - POSTGRES_DB=student
      - POSTGRES_USER=student
      - POSTGRES_PASSWORD=student
    ports:
      - "5432:5432"

  prod_db:
    image: postgres:16.0
    container_name: prod_db
    environment:
      - POSTGRES_DB=prod_db
      - POSTGRES_USER=prod_user
      - POSTGRES_PASSWORD=prod_pass
    ports:
      - "5432:5432"
